### ISSUE TITLE
Resources view crashes when parent environment deleted

### ISSUE THREAD

**Issue by willtsai** [radius-project/dashboard#65]
### Steps to reproduce

1. Deploy an application (e.g. the getting started sample app).
2. Delete the environment to which the application has been deployed, but do not delete the application.
3. Navigate to the "Resources" tab in the Dashboard

### Observed behavior

The page crashes with the following error:
```
Error
TypeError

Message
Cannot read properties of null (reading 'scrollWidth')

Stack Trace
TypeError: Cannot read properties of null (reading 'scrollWidth')
    at pe.value (http://localhost:8001/static/module-backstage.90137cf3.js:37:197926)
    at Ya (http://localhost:8001/static/module-react-dom.e70bfe01.js:14:1661)
    at qa (http://localhost:8001/static/module-react-dom.e70bfe01.js:16:5000)
    at O.unstable_runWithPriority (http://localhost:8001/static/vendor.67e48f7d.js:147:3895)
    at Ze (http://localhost:8001/static/module-react-dom.e70bfe01.js:12:38411)
    at nn (http://localhost:8001/static/module-react-dom.e70bfe01.js:16:1786)
    at Si (http://localhost:8001/static/module-react-dom.e70bfe01.js:14:10983)
    at http://localhost:8001/static/module-react-dom.e70bfe01.js:12:38633
    at O.unstable_runWithPriority (http://localhost:8001/static/vendor.67e48f7d.js:147:3895)
    at Ze (http://localhost:8001/static/module-react-dom.e70bfe01.js:12:38411)
```

### Desired behavior

The "orphaned" resources continue to be displayed, but contain a warning about their "parent" environment having been deleted.

### Would you like to support us?

- [ ] Yes, I would like to support you

AB#12040

**Comment by nithyatsu** [comment]
I dont see this behavior anymore. When I delete an environment, the applications in the env also get deleted. I will test a few more scenarios.

**Comment by willtsai** [comment]
I am also getting the same results on both v0.32 and v0.33 where the app gets deleted along with the env and thus the Dashboard crash does not happen (it accurately shows "no records to display").

<img width="878" alt="image" src="https://github.com/radius-project/dashboard/assets/28876888/3af394b9-dda1-4785-8541-9c35fc9ae71d">

The environment deletion behavior is a bit unclear, however, of the implication that the apps would get deleted along with the env deletion. Thus, @nithyatsu created this additional issue to request enhancement in the env deletion flow to make this clear: https://github.com/radius-project/radius/issues/7529

**Comment by willtsai** [comment]
given that the state of the environment is not reproducible, we are closing this for now, please reopen if the issue persists.
